### ISSUE TITLE
Help post

### ISSUE THREAD

**Issue by Sprtviou** [VanCamNguyen/Human-Detection#1]
Hello, I would like to ask if you write the code according to the algorithm or the paper reference? If there is a relevant paper reference, can you please tell me the relevant information of the paper, such as the title of the paper. Thank you very much for your help.

**Comment by cam-n** [comment]
> Hello, I would like to ask if you write the code according to the algorithm or the paper reference? If there is a relevant paper reference, can you please tell me the relevant information of the paper, such as the title of the paper. Thank you very much for your help.

Hi, you can take a look my technical report as a reference at https://arxiv.org/abs/2205.02689. Thank you.
